Repository ShaneBeee/SkBee, pull requests merged in 2025-08, with the labels that each got.

#845 Component replace effect changes
  src/main/java/com/shanebeestudios/skbee/api/wrapper/ComponentWrapper.java
  src/main/java/com/shanebeestudios/skbee/elements/text/effects/EffComponentReplace.java
  src/test/scripts/elements/text/effects/EffComponentReplace.sk
Labels: enhancement 👷🏼‍♂️, breaking changes 🚨

#846 Add effective name support
  src/main/java/com/shanebeestudios/skbee/elements/text/expressions/ExprEffectiveName.java
Labels: enhancement 👷🏼‍♂️

#841 Dev/patch - Future Patch Release
  src/main/java/com/shanebeestudios/skbee/elements/fastboard/expressions/ExprFastBoardLine.java
  src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprHealthScale.java
  src/test/scripts/general/fastboard.sk
Labels: future 🚀
